import type { SeedReport } from "@/lib/server/repository";
import { creationHistory } from "@/lib/domain/history";

const coordinator = { role: "COORDINATOR", name: "Marta Girma" };

function base(
  partial: Omit<SeedReport, "history" | "actorRole" | "actorName" | "version"> & {
    version?: number;
    historyActor?: { role: string; name: string };
  },
): SeedReport {
  const actor = partial.historyActor ?? { role: "FIELD_WORKER", name: partial.reporterName };
  return {
    ...partial,
    version: partial.version ?? 1,
    actorRole: "FIELD_WORKER",
    actorName: actor.name,
    history: creationHistory(actor.role, actor.name),
  };
}

export function buildSeedReports(): SeedReport[] {
  return [
    base({
      id: "11111111-1111-4111-8111-111111111111",
      clientId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1",
      category: "WATER_POINT",
      description: "The community tap at Hawassa industrial zone has been dry since yesterday morning. Households are queuing at the next point two kilometres away.",
      location: "Hawassa industrial zone, standpipe 4",
      priority: "HIGH",
      status: "SUBMITTED",
      reportedAt: "2026-09-28T06:40:00.000Z",
      reportedTimezone: "UTC+03:00",
      reporterName: "Hana Bekele",
      latitude: 7.0504,
      longitude: 38.4955,
      accuracyMeters: 18,
      serverReceivedAt: "2026-09-28T06:48:00.000Z",
      createdAt: "2026-09-28T06:48:00.000Z",
      updatedAt: "2026-09-28T06:48:00.000Z",
    }),
    {
      ...base({
        id: "22222222-2222-4222-8222-222222222222",
        clientId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2",
        category: "EQUIPMENT",
        description: "The solar array feeding the Bahir Dar clinic vaccine fridge is cracked. The fridge temperature alarm sounded overnight.",
        location: "Bahir Dar clinic, roof array",
        priority: "CRITICAL",
        status: "ASSIGNED",
        reportedAt: "2026-09-25T14:10:00.000Z",
        reportedTimezone: "UTC+03:00",
        reporterName: "Samuel Tadesse",
        assigneeName: "Marta Girma",
        latitude: 11.5742,
        longitude: 37.3614,
        accuracyMeters: 12,
        serverReceivedAt: "2026-09-25T14:16:00.000Z",
        createdAt: "2026-09-25T14:16:00.000Z",
        updatedAt: "2026-09-26T08:05:00.000Z",
        version: 2,
      }),
      extraHistory: [
        {
          action: "STATUS_CHANGED",
          actorRole: coordinator.role,
          actorName: coordinator.name,
          fromValue: "SUBMITTED",
          toValue: "ASSIGNED",
          message: "Status changed from SUBMITTED to ASSIGNED.",
        },
        {
          action: "ASSIGNED",
          actorRole: coordinator.role,
          actorName: coordinator.name,
          fromValue: null,
          toValue: "Marta Girma",
          message: "Assigned to Marta Girma.",
        },
      ],
    },
    {
      ...base({
        id: "33333333-3333-4333-8333-333333333333",
        clientId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa3",
        category: "MAINTENANCE",
        description: "The washout on the Adama feeder road is deep enough that the water tanker cannot pass. Gravel and a culvert repair are needed before the next delivery.",
        location: "Adama feeder road, kilometre 6",
        priority: "MEDIUM",
        status: "IN_PROGRESS",
        reportedAt: "2026-09-22T09:00:00.000Z",
        reportedTimezone: "UTC+03:00",
        reporterName: "Hana Bekele",
        assigneeName: "Yonas Alemu",
        latitude: 8.541,
        longitude: 39.2695,
        accuracyMeters: 40,
        serverReceivedAt: "2026-09-22T09:20:00.000Z",
        createdAt: "2026-09-22T09:20:00.000Z",
        updatedAt: "2026-09-27T11:00:00.000Z",
        version: 3,
      }),
      extraHistory: [
        {
          action: "STATUS_CHANGED",
          actorRole: coordinator.role,
          actorName: coordinator.name,
          fromValue: "SUBMITTED",
          toValue: "ASSIGNED",
          message: "Status changed from SUBMITTED to ASSIGNED.",
        },
        {
          action: "ASSIGNED",
          actorRole: coordinator.role,
          actorName: coordinator.name,
          fromValue: null,
          toValue: "Yonas Alemu",
          message: "Assigned to Yonas Alemu.",
        },
        {
          action: "STATUS_CHANGED",
          actorRole: coordinator.role,
          actorName: coordinator.name,
          fromValue: "ASSIGNED",
          toValue: "IN_PROGRESS",
          message: "Status changed from ASSIGNED to IN_PROGRESS.",
        },
      ],
    },
    base({
      id: "44444444-4444-4444-8444-444444444444",
      clientId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa4",
      category: "SERVICE_INTERRUPTION",
      description: "Grid power to the Mekelle pumping station dropped at dusk and has not returned. The elevated tank is below the reserve line.",
      location: "Mekelle pumping station",
      priority: "HIGH",
      status: "SUBMITTED",
      reportedAt: "2026-09-30T16:05:00.000Z",
      reportedTimezone: "UTC+03:00",
      reporterName: "Sara Mohammed",
      latitude: 13.4967,
      longitude: 39.4753,
      accuracyMeters: 25,
      serverReceivedAt: "2026-09-30T16:11:00.000Z",
      createdAt: "2026-09-30T16:11:00.000Z",
      updatedAt: "2026-09-30T16:11:00.000Z",
    }),
    {
      ...base({
        id: "55555555-5555-4555-8555-555555555555",
        clientId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa5",
        category: "SAFETY_CONCERN",
        description: "An exposed cable is hanging into the walkway at the Dire Dawa warehouse loading bay. Staff are routing around it, but the night shift will not see it clearly.",
        location: "Dire Dawa warehouse, bay 2",
        priority: "CRITICAL",
        status: "IN_PROGRESS",
        reportedAt: "2026-09-29T18:20:00.000Z",
        reportedTimezone: "UTC+03:00",
        reporterName: "Samuel Tadesse",
        assigneeName: "Marta Girma",
        latitude: 9.6009,
        longitude: 41.8501,
        accuracyMeters: 15,
        serverReceivedAt: "2026-09-29T18:24:00.000Z",
        createdAt: "2026-09-29T18:24:00.000Z",
        updatedAt: "2026-09-30T07:40:00.000Z",
        version: 3,
      }),
      extraHistory: [
        {
          action: "PRIORITY_CHANGED",
          actorRole: coordinator.role,
          actorName: coordinator.name,
          fromValue: "HIGH",
          toValue: "CRITICAL",
          message: "Priority changed from HIGH to CRITICAL.",
        },
        {
          action: "STATUS_CHANGED",
          actorRole: coordinator.role,
          actorName: coordinator.name,
          fromValue: "SUBMITTED",
          toValue: "ASSIGNED",
          message: "Status changed from SUBMITTED to ASSIGNED.",
        },
        {
          action: "ASSIGNED",
          actorRole: coordinator.role,
          actorName: coordinator.name,
          fromValue: null,
          toValue: "Marta Girma",
          message: "Assigned to Marta Girma.",
        },
        {
          action: "STATUS_CHANGED",
          actorRole: coordinator.role,
          actorName: coordinator.name,
          fromValue: "ASSIGNED",
          toValue: "IN_PROGRESS",
          message: "Status changed from ASSIGNED to IN_PROGRESS.",
        },
      ],
    },
    {
      ...base({
        id: "66666666-6666-4666-8666-666666666666",
        clientId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa6",
        category: "MAINTENANCE",
        description: "The Jimma hand pump handle was replaced and the soak-away was cleared. The point is producing water again.",
        location: "Jimma, kebele 7 hand pump",
        priority: "LOW",
        status: "RESOLVED",
        reportedAt: "2026-09-18T08:15:00.000Z",
        reportedTimezone: "UTC+03:00",
        reporterName: "Hana Bekele",
        assigneeName: "Yonas Alemu",
        latitude: 7.6731,
        longitude: 36.8344,
        accuracyMeters: 22,
        serverReceivedAt: "2026-09-18T08:30:00.000Z",
        createdAt: "2026-09-18T08:30:00.000Z",
        updatedAt: "2026-09-21T15:10:00.000Z",
        version: 4,
      }),
      extraHistory: [
        {
          action: "STATUS_CHANGED",
          actorRole: coordinator.role,
          actorName: coordinator.name,
          fromValue: "IN_PROGRESS",
          toValue: "RESOLVED",
          message: "Status changed from IN_PROGRESS to RESOLVED. Pump tested with the water committee.",
        },
      ],
    },
    {
      ...base({
        id: "77777777-7777-4777-8777-777777777777",
        clientId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa7",
        category: "OTHER",
        description: "Report asked for a new office chair at the woreda desk. That is outside the field maintenance programme.",
        location: "Gondar woreda desk",
        priority: "LOW",
        status: "REJECTED",
        reportedAt: "2026-09-19T11:00:00.000Z",
        reportedTimezone: "UTC+03:00",
        reporterName: "Sara Mohammed",
        latitude: 12.603,
        longitude: 37.4521,
        accuracyMeters: 30,
        serverReceivedAt: "2026-09-19T11:12:00.000Z",
        createdAt: "2026-09-19T11:12:00.000Z",
        updatedAt: "2026-09-19T16:45:00.000Z",
        version: 2,
      }),
      extraHistory: [
        {
          action: "STATUS_CHANGED",
          actorRole: coordinator.role,
          actorName: coordinator.name,
          fromValue: "SUBMITTED",
          toValue: "REJECTED",
          message: "Status changed from SUBMITTED to REJECTED. Outside the maintenance programme.",
        },
      ],
    },
  ];
}
